<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add to cart</name>
   <tag></tag>
   <elementGuidId>bda16701-1e63-4ded-ba6c-05c02de39d35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='a-autoid-6-announce']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#a-autoid-6-announce</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6045f1c7-b71d-462f-86c9-ceb3a2cfd065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-text</value>
      <webElementGuid>5a9920d4-6c96-4b50-9377-9dbce5f46dc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d345e9b1-fa00-4e82-b1ab-d710e3b61f74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a-autoid-6-announce</value>
      <webElementGuid>faf19cdd-8746-47ba-9bd9-cfaea7f9755b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add to cart</value>
      <webElementGuid>305cbdb6-5148-49e8-9ac1-af07f7a0f144</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a-autoid-6-announce&quot;)</value>
      <webElementGuid>3b402afa-a76e-4343-acd4-1fafacb7e3e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='a-autoid-6-announce']</value>
      <webElementGuid>0f7e13a6-3272-4e60-bdcd-aa5f69ee6adf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='a-autoid-6']/span/button</value>
      <webElementGuid>c2f3debd-3fb3-4c5e-a0d7-896f87cf23fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/span/div/div/div[2]/div[5]/span/div/div/form/span/div/div/span/span/button</value>
      <webElementGuid>20217ef4-07a1-4129-8022-d3deb497fc5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'a-autoid-6-announce' and (text() = 'Add to cart' or . = 'Add to cart')]</value>
      <webElementGuid>caa6b7f6-18a4-44a6-b1b5-716935d4ff75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
