<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Orders</name>
   <tag></tag>
   <elementGuidId>41a90462-5435-4455-8055-206cef7801e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nav-orders > span.nav-line-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='nav-orders']/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>98570dbc-b718-4965-8bd5-273d7d4c1a52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-line-2</value>
      <webElementGuid>9ea192f6-6e5e-4495-9c76-dbace46405a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>&amp; Orders</value>
      <webElementGuid>3bc806b1-0268-4377-9b5d-83add0e16a66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-orders&quot;)/span[@class=&quot;nav-line-2&quot;]</value>
      <webElementGuid>92b31941-779a-4d49-bce0-1f909a9dc931</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='nav-orders']/span[2]</value>
      <webElementGuid>a0e30101-b9fa-4cd9-ac52-1cddb191a904</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/span[2]</value>
      <webElementGuid>129a3e39-5cc1-401a-9d69-88b99a8ec470</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '&amp; Orders' or . = '&amp; Orders')]</value>
      <webElementGuid>2be4cfc1-9e02-40cf-93df-525ae1b5370b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
